"""MCP server — Quiver Quantitative API (auto-generated by /mcp creator).

Quiver Quant aggregates alternative data: congressional trades, insider
transactions, government contracts, WSB sentiment, lobbying, and more.

Auth: Bearer token via QUIVER_QUANT_KEY env var.
Free tier / demo key returns ~1000 records per endpoint.
Real key: https://www.quiverquant.com/quiverapi/
"""
import json
import logging
import os
import sys
from typing import Optional

import httpx
from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP

load_dotenv()
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s", stream=sys.stderr)
logger = logging.getLogger("quiverquant-mcp")

mcp = FastMCP("quiverquant")

_BASE = "https://api.quiverquant.com"
_API_KEY = os.environ.get("QUIVER_QUANT_KEY", "demo")
_HEADERS = {
    "Authorization": f"Bearer {_API_KEY}",
    "Accept": "application/json",
    "User-Agent": "AI.Trader/1.0",
}

if _API_KEY == "demo":
    logger.warning("QUIVER_QUANT_KEY=demo — rate-limited to ~1000 records. Set a real key for full access.")

_client: Optional[httpx.AsyncClient] = None


async def _get_client() -> httpx.AsyncClient:
    global _client
    if _client is None or _client.is_closed:
        _client = httpx.AsyncClient(base_url=_BASE, headers=_HEADERS, timeout=30.0)
    return _client


async def _get(path: str, params: Optional[dict] = None) -> dict | list:
    client = await _get_client()
    try:
        r = await client.get(path, params=params or {})
        r.raise_for_status()
        return r.json()
    except httpx.HTTPStatusError as e:
        return {"error": f"HTTP {e.response.status_code}: {e.response.text[:300]}"}
    except Exception as e:
        return {"error": str(e)}


# ── Congressional Trading ─────────────────────────────────────────────────────

@mcp.tool()
async def get_congress_trades_live() -> str:
    """All recent congressional stock disclosures (STOCK Act filings).

    Returns a list of trades with: Representative, Ticker, Transaction,
    Range, TransactionDate, ReportDate, House, Party, ExcessReturn.
    """
    data = await _get("/beta/live/congresstrading")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


@mcp.tool()
async def get_congress_trades_by_ticker(ticker: str) -> str:
    """Historical congressional trades for a specific stock ticker.

    Args:
        ticker: Stock ticker symbol e.g. AAPL, NVDA, MSFT
    """
    data = await _get(f"/beta/historical/congresstrading/{ticker.upper()}")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


# ── Insider Trading ────────────────────────────────────────────────────────────

@mcp.tool()
async def get_insider_trades_live() -> str:
    """Live insider trading transactions (SEC Form 4 filings).

    Returns officer/director buy and sell transactions with share counts
    and transaction values.
    """
    data = await _get("/beta/live/insiders")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


@mcp.tool()
async def get_insider_trades_by_ticker(ticker: str) -> str:
    """Historical insider trades for a specific stock ticker.

    Args:
        ticker: Stock ticker symbol e.g. AAPL, NVDA, MSFT
    """
    data = await _get(f"/beta/historical/insiders/{ticker.upper()}")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


# ── WallStreetBets ─────────────────────────────────────────────────────────────

@mcp.tool()
async def get_wsb_mentions() -> str:
    """Live WallStreetBets (r/wallstreetbets) stock mention counts and sentiment.

    Returns tickers ranked by mention frequency with sentiment scores.
    Useful for retail sentiment signals.
    """
    data = await _get("/beta/live/wallstreetbets")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


@mcp.tool()
async def get_wsb_mentions_by_ticker(ticker: str) -> str:
    """Historical WallStreetBets mentions for a specific ticker.

    Args:
        ticker: Stock ticker symbol e.g. GME, AMC, NVDA
    """
    data = await _get(f"/beta/historical/wallstreetbets/{ticker.upper()}")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


# ── Government Contracts ───────────────────────────────────────────────────────

@mcp.tool()
async def get_gov_contracts_live() -> str:
    """Live US government contract awards (from USASpending.gov).

    Returns company-level contract awards useful for identifying
    defense and infrastructure spending beneficiaries.
    """
    data = await _get("/beta/live/govcontract")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


@mcp.tool()
async def get_gov_contracts_by_ticker(ticker: str) -> str:
    """Historical government contracts for a specific company by ticker.

    Args:
        ticker: Stock ticker symbol e.g. LMT, RTX, BA
    """
    data = await _get(f"/beta/historical/govcontract/{ticker.upper()}")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


# ── Lobbying ───────────────────────────────────────────────────────────────────

@mcp.tool()
async def get_lobbying_live() -> str:
    """Live corporate lobbying disclosures filed with Congress.

    Returns company lobbying spend and issue areas — useful for
    identifying regulatory risk and political influence signals.
    """
    data = await _get("/beta/live/lobbying")
    return json.dumps(data, indent=2) if not isinstance(data, dict) or "error" not in data else str(data)


# ── Generic Explorer ───────────────────────────────────────────────────────────

@mcp.tool()
async def explore_endpoint(path: str) -> str:
    """Fetch any Quiver Quant API endpoint directly.

    Useful for discovering undocumented endpoints or fetching data
    not covered by the specific tools above.

    Args:
        path: API path starting with /beta/ e.g. /beta/live/congresstrading
    """
    data = await _get(path)
    if isinstance(data, list):
        count = len(data)
        keys = list(data[0].keys()) if data else []
        preview = json.dumps(data[:3], indent=2)
        return f"Array: {count} items\nKeys: {keys}\n\nFirst 3:\n{preview}"
    return json.dumps(data, indent=2)


if __name__ == "__main__":
    logger.info("Quiver Quant MCP server starting...")
    mcp.run(transport="stdio")
